function dataSpag() {
    return [{
        "name": "韩都衣舍旗舰店",
        "src": "https://detail.tmall.com/item.htm?id=536047980017",
        "类别": "女装",
        "返利": "5%-15%",
        "desc": "女装销量总冠军"
    }, {
        "name": "aviva_j",
        "src": "https://aviva-j.taobao.com/",
        "类别": "女装",
        "返利": 0.065,
        "desc": "高端小众女装"
    }, {
        "name": "papa丢丢",
        "src": "https://honey-diudiu.taobao.com/",
        "类别": "女装",
        "返利": "6%-20%",
        "desc": "时尚韩国风"
    }, {
        "name": "有货",
        "src": "https://yoho.tmall.com/",
        "类别": "男装",
        "返利": 0.08,
        "desc": "潮流购物中心"
    }, {
        "name": "简单点0202",
        "src": "https://shop70736051.taobao.com/",
        "类别": "男装",
        "返利": 0.05,
        "desc": "港仔文艺男装"
    }, {
        "name": "小猪班纳旗舰店",
        "src": "https://pepco.tmall.com/",
        "类别": "童装",
        "返利": 0.08,
        "desc": "品质童装首选"
    }, {
        "name": "安奈儿旗舰店",
        "src": "https://annil.tmall.com/",
        "类别": "童装",
        "返利": 0.04,
        "desc": "20年·伴你童行"
    }, {
        "name": "suki水蓝色眼泪",
        "src": "https://shop34320623.taobao.com/",
        "类别": "女鞋",
        "返利": "5%-6%",
        "desc": "高级定制女鞋"
    }, {
        "name": "doms鞋类旗舰店",
        "src": "https://doms.tmall.com/",
        "类别": "女鞋",
        "返利": "8%-10%",
        "desc": "欧美经典 专注品质"
    }, {
        "name": "黑眼袋袋箱包旗舰店",
        "src": "https://dblack.tmall.com/",
        "类别": "女包",
        "返利": "5%-6%",
        "desc": "爆款集合潮包店"
    }, {
        "name": "伊米妮旗舰店",
        "src": "https://emini.tmall.com/",
        "类别": "女包",
        "返利": 0.045,
        "desc": "只卖真皮包"
    }, {
        "name": "mbox饰品旗舰店",
        "src": "https://mbox.tmall.com/",
        "类别": "饰品",
        "返利": "10.5%-24%",
        "desc": "女人需要精致"
    }, {
        "name": "路过十里铺",
        "src": "https://ssboots.taobao.com/",
        "类别": "饰品",
        "返利": 0.15,
        "desc": "打造最美的饰品"
    }, {
        "name": "litfly旗舰店",
        "src": "http://shop72775803.taobao.com",
        "类别": "美妆",
        "返利": 0.04,
        "desc": "梦幻彩妆工具"
    }, {
        "name": "美丽工匠化妆品旗舰店",
        "src": "https://beautyartisan.tmall.com/",
        "类别": "美妆",
        "返利": 0.082,
        "desc": "专注美妆生活"
    }, {
        "name": "卫龙食品旗舰店",
        "src": "https://weilongshipin.tmall.com/",
        "类别": "零食",
        "返利": 0.08,
        "desc": "用辣条征服全世界"
    }, {
        "name": "来伊份官方旗舰店",
        "src": "https://laiyifen.tmall.com/",
        "类别": "零食",
        "返利": 0.065,
        "desc": "领鲜到底 为你所爱"
    }, {
        "name": "金华金字火腿旗舰店",
        "src": "https://jinzi.tmall.com/",
        "类别": "零食",
        "返利": 0.05,
        "desc": "上市公司 精制出品"
    }, {
        "name": "烟雨集life旗舰店",
        "src": "https://yanyujilife.tmall.com/",
        "类别": "春年装饰",
        "返利": 0.035,
        "desc": "年品“鸡”动上线"
    }, {
        "name": "粉爱粉爱你旗舰店",
        "src": "https://fenaifenaini.tmall.com/",
        "类别": "春年装饰",
        "返利": 0.055,
        "desc": "抢年货 过新年"
    }, {
        "name": "光彩年华旗舰店",
        "src": "https://gcnh.tmall.com/",
        "类别": "礼物",
        "返利": 0.038,
        "desc": "创意礼品店"
    }, {
        "name": "englishbenbenni",
        "src": "https://meiliruyun.jiyoujia.com/",
        "类别": "礼物",
        "返利": 0.1,
        "desc": "用心送出每一份礼物"
    }]
}